php:
  preset: laravel
<<<<<<< HEAD
  version: 8
=======
>>>>>>> 02b12afbcfc48a7aa01129d319afbe25f6726349
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
<<<<<<< HEAD
=======
      - server.php
>>>>>>> 02b12afbcfc48a7aa01129d319afbe25f6726349
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
